#!/bin/bash
# Uses cssminifier.com service to minify specified .css files.
#
# Instructions: 
#   1) Set PATH to path to .css files from this file
#   2) Add filenames of desired .css files, omitting path and extension, to FILES

PATH="static/css"
FILES=(bootstrap-custom blog) # Omit extensions

for css_file in ${FILES[*]}; do
    COMBINED=$PATH/""$css_file""
    if [ ! -f "$COMBINED".css ]; then
        echo "File not found - $CONBINED" >&2
    else
        /usr/bin/curl -X POST -s --data-urlencode "input@""$COMBINED"".css" http://cssminifier.com/raw > "$COMBINED".min.css
    fi
done
