#!/bin/bash
# Recompiles Bootstrap and copies new .css, .min.css, and .css.map files
# to location of stylesheets in static files.
#
# Instructions: 
#    1) Set CSS_PATH to directory to which Boostrap CSS should be copied
#    2) Set BSDIR to location of Bootstrap source

CSS_PATH="static/css/"
THISDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BSDIR=~/dev/bootstrap-3.2.0-portfolio/
FILE1="dist/css/bootstrap.css"
FILE2="dist/css/bootstrap.css.map"
FILE3="dist/css/bootstrap.min.css"

cd $BSDIR
grunt dist
cd "$THISDIR"
cp -v -t "$CSS_PATH" ""$BSDIR""$FILE1 ""$BSDIR""$FILE2 ""$BSDIR""$FILE3